server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    add_header X-Frame-Options "SAMEORIGIN"; #заголовки для безопастности
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; } #Эти блоки отключают логирование для этих часто запрашиваемых файлов, чтобы не захламлять логи ошибками при их отсутствии
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_pass app:9000;   # обратите внимание: app – это имя сервиса из docker-compose
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* { #Это правило запрещает доступ к любым файлам/папкам, начинающимся с точки (скрытые файлы), за исключением /.well-known/. /.well-known используется для различных протоколов (например, Let's Encrypt). Таким образом, защищаются такие файлы, как .env, .git, .htaccess и т.д
        deny all;
    }
}
